cmd/babylond/cmd/flags.go, cmd/babylond/cmd/genesis.go, cmd/babylond/cmd/testnet.go
These flags will help us control the inflation rate when we create a genesis file for testnet purposes.
=> prepare-genesis cmd: Add flags related to inflation

app/app.go, testutil/keeper/btccheckpoint.go, x/btccheckpoint/abci.go, x/btccheckpoint/keeper/hooks.go, x/btccheckpoint/keeper/keeper.go, x/btccheckpoint/module.go, x/btccheckpoint/types/keys.go
Currently most costly babylon msg is Insert Header msg from btc light client. The difference is in order of magnitude range. The main reason is that btclightclient exposes hooks for header events to which btccheckpoint subscribes. With each header update it check status of every checkpoint of every non finalized epoch. This mean that gas cost of this operation is around O(numberOfNonFinlizedEpochs * numberOfCheckpointsInEachNonFinalizedEpoch) (+ some some cost of light client itself).
This pr proposes to move all checking logic into EndBlock callback and to use local transient store to check if btc light client have been updated during current block execution.
This:
- reduces gas cost of inserting btc header to only the gas costs of btc light client itself (operations on transient store …
=> fix gas cost of insert header

app/utils.go, client/tx/tx.go, cmd/babylond/cmd/custom_babylon_config.go, types/signer_config.go, x/checkpointing/keeper/bls_signer.go, x/checkpointing/keeper/bls_signer_test.go, x/checkpointing/keeper/keeper.go, x/checkpointing/keeper/msg_server.go
This PR fixes #168 
The fee of sending a BLS-sig tx was hardcoded. This PR estimates the fee by calculating the gas. This PR also adds two gas-related settings, `gas-price` and `gas-adjustment` in the `app.toml` to calculate the actual `fee=calculated_gas * gas_adjustment * gas_price`.
This PR also removed the test of `SendBlsSig` as the gas calculation is not implemented for testing. Instead, this PR is well tested using [babylon-deployment](https://github.com/babylonchain/babylon-deployment).
=> feat: Checkpointing/Add fee estimation in sending BLS-sig tx

testutil/mocks/checkpointing_expected_keepers.go, x/checkpointing/keeper/msg_server.go, x/checkpointing/types/expected_keepers.go, x/epoching/keeper/staking_functions.go, x/epoching/types/expected_keepers.go
This PR migrates stateless checks on `MsgCreateValidator` to `MsgWrappedCreateValidator`. This ensures any `MsgWrappedCreateValidator` attaching a `MsgCreateValidator` that cannot satisfy stateless checks will be rejected immediately rather than at the end of an epoch.
This fix does not affect the epoching mechanism since these checks will be performed at the end of an epoch anyway. It's more about UX -- any mistake that fails stateless checks in `MsgCreateValidator` will be notified immediately. This is inspired by the messages in Discord.
=> checkpointing: stateless checks on `MsgCreateValidator`

app/app.go, testutil/keeper/epoching.go, x/checkpointing/keeper/msg_server_test.go, x/epoching/keeper/keeper.go, x/epoching/keeper/staking_functions.go, x/epoching/types/errors.go
This PR fixed #317 and added relevant fuzz tests. To support the check of delegator balance, this PR added the `BankKeeper` to the epoching module
=> chore: Add balance check before inserting MsgWrappedCreateValidator into the epoch message queue

.circleci/config.yml
Same logic as the one described on https://github.com/babylonchain/babylonscan/pull/25.
=> CI: Build and push Docker image to ECR

go.mod, go.sum, testutil/datagen/tendermint.go, x/zoneconcierge/keeper/grpc_query_test.go, x/zoneconcierge/keeper/hooks.go, x/zoneconcierge/keeper/keeper_test.go
New version has been simplified due to usage of ibc-go v7 
New version can work with other types of light clients not only tendermint
=> Use new version for our fork of ibc go

Makefile, app/app.go, app/app_test.go, app/test_helpers.go, client/docs/docs.go, cmd/babylond/cmd/custom_babylon_config.go, cmd/babylond/cmd/root.go, contrib/images/babylond-dlv/Dockerfile, contrib/images/babylond-env/Dockerfile, go.mod, go.sum, simapp/sim_bench_test.go, simapp/sim_test.go
Initial integration with wasmd.
Currently it uses this commit of wasmd repo - https://github.com/CosmWasm/wasmd/tree/7e936c7fffb6f489ed9ecb797a7a2823a032b10b
There will be at least one follow up task - https://github.com/babylonchain/babylon/issues/335
=> Integrate wasmd

.circleci/config.yml, test/e2e/containers/config.go, test/e2e/containers/containers.go, test/e2e/e2e_test.go
New version of hermes supports new version of tendermint, it is possible to re-enable e2e tests.
=> Re-enable e2e tests

.circleci/config.yml
The sequential execution of all of the CircleCI steps takes too long. In this PR we parallelize them to improve CI times.
=> chore: Parallelize CircleCI lint build

x/zoneconcierge/keeper/proof_epoch_sealed.go
This PR fixes a bug when proving a validator set is committed to the app hash.
=> fix: fixing the bug in generating proof of sealed epoch

x/zoneconcierge/keeper/query_kvstore.go, x/zoneconcierge/keeper/query_kvstore_test.go
This PR fixes a bug in `ProveEpochSealed`. 
When executing an ABCI query `abci.RequestQuery`, one needs to feed a `height`, such that the node will reply an inclusion proof of the queried KV pair against the header at `height+1`. 
We use this ABCI query for generating proofs of inclusion for the validator set and the metadata of epoch `i` against the sealer header, i.e., the 2nd header of epoch `i+1`. In order to allow verifier to verify the proofs against the sealer header, the ABCI query should be given height `queryHeight-1` rather than `queryHeight`, where `queryHeight` will be the sealer header's height. This PR fixes the bug where we use `queryHeight` rather than `queryHeight - 1`.
The corresponding unit test is also fixed.
=> fix: fix query height in `ProveEpochSealed`

x/epoching/types/errors.go
The `use wrapped versions instead` message is a bit cryptic and has led to many people asking us what they should do. This PR adds some more details on what one can do to resolve the issue.
=> chore: Use more descriptive error message for using wrapped transactions

cmd/babylond/cmd/testnet.go
The `testnet` command no longer produced gRPC addresses with the `0.0.0.0` host but instead `localhost`. Given that the `testnet` command leads to the generation of config files for the devnet it's more helpful if the IP is the host's IP (similar to what we do for P2P and RPC addresses).
=> fix: Make testnet command produce addresses bound to the host IP

go.mod, go.sum
The updates will resolve the current dependabot security alerts.
=> chore: Update runc and docker dependencies due to security alerts

x/btccheckpoint/keeper/keeper.go, x/btccheckpoint/keeper/keeper_test.go
While looking for ways of optimizing `BtcCheckpointInfo` endpoint I encountered bug in getting submission btc info, which could lead to misindexing of transaction.
This pr fixes the bug and provides set of tests triggering given problem.
In general I think we need ADR for describing how we decide which submission is the best. It can be done when we will start working on rewards.
=> Fix bug in submission btc info

.circleci/config.yml, btctxformatter/formatter_test.go
On the [rpc-client repository](https://github.com/babylonchain/rpc-client/pull/33) I encountered issues due to the Ubuntu image being used having Go 1.18 installed instead of the 1.20 version that we use. These were fixed when I used an image with the appropriate version installed, so figured to do the same here.
Given that we use Docker for some of the build steps this fails. Will investigate further.
=> chore: circleci: Use image with go 1.20.3 installed

x/btccheckpoint/keeper/msg_server_test.go
Adds proper fuzz test for the logic which handles epoch finalization/confirmation.
=> Add fuzz test for epoch finalization/confirmation

x/btccheckpoint/module.go, x/btclightclient/module.go, x/checkpointing/module.go, x/epoching/module.go, x/monitor/module.go
According to docs:
```
// ConsensusVersion is a sequence number for state-breaking change of the
// module. It should be incremented on each consensus-breaking change
// introduced by the module. To avoid wrong/empty versions, the initial version
// should be set to 1.
```
As our modules are pre-release, it makes sense for them to return `1`.  `zoneconcierge` module was the only module which did the right thing.
=> Fix consensus version in our custom modules

test/integration_test.go
With some unfortunate timing during integration test, babylon nodes could be already be a bit after block 7, and current epoch can be larger than 2. As in this test we only check that nodes are progressing, it is enough to require that `currentEpoch >= 2`
=> Fix non-determinism in integration test

app/app.go, go.mod, go.sum
Small pr to bump wasmd to rc2 versions.
One thing I noticed, both ibc-go and wasmd uses `FeeKeeper` as their `ICS4Wrapper` implementation in their test-apps (https://github.com/cosmos/ibc-go/blob/main/testing/simapp/app.go#LL413C6-L413C18), where we only use `ChannelKeeper`. 
From what I understand `FeeKeeper` is actually enables https://github.com/cosmos/ibc/tree/main/spec/app/ics-029-fee-payment, which is scheme used to pay rewards to relayers. It seems like a good idea to enable it also on Babylon . What do you think @SebastianElvis  ?
=> Bump wasmd to rc2

go.mod, go.sum
To fix [dependabot alert](https://github.com/babylonchain/babylon/security/dependabot/12)
=> Bump vulnerable docker/distribution

app/app.go
Wires up and uses ibc fee module. Module is implementation of https://github.com/cosmos/ibc/tree/main/spec/app/ics-029-fee-payment which spec of relayer incentivization.
To wire up fee module there are two changes necessary:
1. Pass FeeKeeper as ics4wrapper to other ibc modules (transferKeeper, zoneconciergeKeeeper, wasmKeeper)
2. Create `ibcfee.NewIBCMiddleware` and route for each ibc module used
Imo it makes sense for Babylon to enable this module, as we will be using a lot of IBC to distribute checkpoints to other cosmos zones.
=> Use fee module

contrib/images/babylond/Dockerfile
The current Dockerfile gets the last commit of the current branch to build by default. Sometimes we want to test uncommitted changes locally. This PR proposes to opt out the version in the sense that 
- by default, Dockerfile builds with the latest code (even uncommitted), 
- one can specify its preferred version by setting an nonempty $VERSION
=> dockerfile: opt out version when building

README.md
Hi, reading the doc I found out the current discord link is down, so I figured I would correct it myself instead of opening an issue and requiring someone to open a PR.
I found the new discord link in the Babylon's twitter bio.
That's it, doesn't require testing or changelog entry.
=> README: updating discord link

client/docs/swagger-ui/swagger.yaml, proto/babylon/epoching/v1/epoching.proto, x/epoching/README.md, x/epoching/abci.go, x/epoching/keeper/epochs.go, x/epoching/types/epoching.pb.go, x/finality/README.md, x/finality/types/tx.pb.go, x/zoneconcierge/README.md
Migrated from private repo. Comments there are already addressed.
---
Fixes [BM-944](https://babylon-chain.atlassian.net/browse/BM-944)
This PR provides documentation for the epoching module. The concept section is adapted/rephrased from https://docs.babylonchain.io/docs/developer-guides/modules/epoching while the rest is new.
=> doc: documentation for the epoching module

Makefile, contrib/images/cosmos-relayer/Dockerfile, test/e2e/btc_timestamping_phase2_rly_test.go, test/e2e/configurer/base.go, test/e2e/containers/config.go
A small PR with some improvements  / follow-up of #419.
This uses a pre-built public `cosmos-relayer` image to try and save some time during e2e tests. The image _has_ to be built for the same platform the CI is running on (`amd64`), or the phase 2 tests will fail with obscure error messages.
=> BTC time-stamping phase 2 tests follow-up

x/zoneconcierge/README.md
This PR provides a second revision of ZoneConcierge module's documentation, including
- a new "concepts" section for describing the motivation and overall design of the module.
- move "hooks" and "posthandlers" sections to new sections since they are a part of module spec
- update the spec of phase2 integration according to #413 
- proofreading and rewrite some parts
=> doc: more details in ZoneConcierge's documentation

contrib/images/babylond/Dockerfile, test/e2e/btc_staking_e2e_test.go, test/e2e/configurer/chain/chain.go, test/e2e/configurer/chain/commands.go, test/e2e/configurer/chain/commands_btcstaking.go, test/e2e/configurer/chain/node.go, test/e2e/ibc_transfer_e2e_test.go
Noticed some issues with the BTCStaking tests failing from time to time:
https://app.circleci.com/pipelines/github/babylonchain/babylon/1891/workflows/5e99488b-f864-45ad-856b-a01540cacb0c.
Turns out this is (likely / probably) a wasmer bug, with a [workaround](https://github.com/wasmerio/wasmer/issues/1568#issuecomment-1868697116) that was reported some time ago by Injective.
Changed the babylon docker image to use Debian bookworm instead of Alpine Linux. Seems to be working ~~(though not in CI)~~.
Also, did some syntax fixes, and robustness improvements of BTC Staking checks.
=> E2e test improvements

x/btclightclient/README.md
Initial version of btc light client docs.
Note: one thing I have noticed during writing the docs is that with current btc data model event `EventBTCHeaderInserted` (and hook) is no different than `EventBTCRollForward`  i.e every header inserted rolls the chain forward. Any objections to removing it ?
=> docs for btc light client

cmd/babylond/cmd/custom_babylon_config.go, cmd/babylond/cmd/root.go, cmd/babylond/cmd/testnet.go, test/e2e/initialization/node.go
This was used for the BLS signer process. Don't think it's being used anywhere else.
=> chore: Remove leftover signer config

crypto/bip322/bip322.go, crypto/bip322/bip322_test.go, crypto/bip322/witness.go, x/btcstaking/types/pop.go, x/btcstaking/types/pop_test.go
- add bip322 sig generation for p2tr address and p2wpkh  address
- improve types in api
- properly check that btc address used in bip322, corresponds to bip340 public key
TODO:
=> Fix bip322 pop

x/btcstaking/keeper/bench_test.go, x/finality/keeper/bench_test.go, x/finality/keeper/public_randomness_bench_test.go, x/finality/keeper/tallying_bench_test.go, x/finality/keeper/votes_bench_test.go
This PR introduces benchmark tests for key operations in the finality module.
The goal is to identify performance bottlenecks and the corresponding issues in the normal operation of finality module, in a quick and dirty way. The PR suspects the following potential performance hotspots:
- committing randomness
- adding finality signatures
- tallying blocks
Thus this PR introduces 3 groups of benchmark tests:
- `BenchmarkCommitPubRandList`: repeatedly submits a given number of public randomness
- `BenchmarkAddFinalitySig`: repeatedly submits 1 finality signature
- `BenchmarkTallyBlocks`: repeatedly tallies blocks with a given number of finality providers
The overall result is that the above scenarios do not have performance issues.
```log
BenchmarkCommitPubRandList_10000-16          100 …
```
=> bench: benchmarking finality module

x/btcstaking/abci.go, x/btcstaking/keeper/incentive.go, x/btcstaking/keeper/incentive_test.go, x/btcstaking/keeper/keeper.go, x/btcstaking/keeper/voting_power_table.go, x/btcstaking/keeper/voting_power_table_test.go, x/finality/keeper/keeper.go, x/finality/types/expected_keepers.go, x/finality/types/mocked_keepers.go
This PR optimises the access on iterating all BTC delegations, including
- introducing `IterateActiveFPsAndBTCDelegations` that iterates over all BTC delagtions under non-slashed finality providers. It takes a handler function as input in order to be generic to any usage of iterating BTC delegations.
- merging the computation of voting power table and reward distribution cache by using `IterateActiveFPsAndBTCDelegations`. This reduces DB footprint of `BeginBlock` of BTC staking module by ~half.
This PR gives a speedup and CPU/memory foorprint reduction of 2x for BTC staking module's `BeginBlock`. After this PR, with 10k BTC delegations, `BeginBlock` takes ~0.006s in benchmarking tests.
```log
// current `dev`
BenchmarkBeginBlock_10_100-16               1707          12924721 ns/op …
```
=> btcstaking: optimise iterative access to BTC delegations

x/btcstaking/keeper/btc_delegators.go, x/btcstaking/keeper/msg_server.go, x/btcstaking/types/btc_delegation.go, x/btcstaking/types/btc_slashing_tx.go, x/btcstaking/types/btc_undelegation.go
Small non-breaking refactor of adding covenant signatures, also fixes some issues when processing covenant signatures message. Up until now:
- for every received covenant signatures message, we retrieved delegation from database two times: once at the beginning of processing message, and the second time when saving it to database (as our save was actually save-modify-write). 
Just to put that in context, for 100k delegation, this is 100k not necessary random database reads. Or actually more, as even  when we already reached quorum, and we were ignoring incoming covenant signatures, we still retrieved delegation second time from database just to not apply any changes to it.
- even though we ignored received signatures if quorum was already reached we emitted …
=> Refactor adding covenant signatures

x/btcstaking/keeper/btc_delegators.go, x/btcstaking/keeper/keeper.go, x/btcstaking/keeper/voting_power_table.go
There is a non determinism due to the usage of [map](https://github.com/babylonchain/babylon/commit/6f60ff0e608271f01fdb0e8072deafa736c8c951#diff-c53a7810ec5c6d9f2687565eed257f497247c84a8f226cba66eba692c2913a8aR73-R79). This PR fixes it by avoiding using maps. It breaks down the nested iterators into two functions and handles each finality provider sequentially. Only array is used.
=> fix non determinism in `BeginBlock`

testutil/datagen/incentive.go
`FuzzWithdrawReward` was [flaky](https://app.circleci.com/pipelines/github/babylonchain/babylon/2019/workflows/6b2a669d-867e-446e-a218-f7d49b7090df/jobs/3399) because `amount` [here](https://github.com/babylonchain/babylon/blob/396a712297f97cd8ca225bcea81ee9b02dada991/testutil/datagen/incentive.go#L65-L66) might be 1, making `RandomInt` panic. This PR fixes it by adding a check. Fuzzed the test locally and the fix works.
=> fix: fix flaky test `FuzzWithdrawReward`

CHANGELOG.md, Makefile, scripts/update_changelog.sh
Wrapper around `github_changelog_generator` that simplifies keeping the changelog updated.
To use it, you first need to install https://github.com/github-changelog-generator/github-changelog-generator of course.
Also, though it can be used without it, it's convenient to have a token called `CHANGELOG_GITHUB_TOKEN`, to increase the number of API requests that can you do when generating the changelog entries.
See https://github.com/github-changelog-generator/github-changelog-generator?tab=readme-ov-file#github-token for instructions on how to generate and set the token.
A convenient way to use it, is with the `-u` (upcoming) flag, to pass a version tag that that is not existing yet in the repo.
That way you can update the changelog in a release branch, before tagging the new version. And …
=> Add CHANGELOG

x/btcstaking/keeper/btc_delegators.go, x/btcstaking/keeper/keeper_test.go, x/btcstaking/keeper/msg_server_test.go
Git cleaned up version of @SebastianElvis fix - https://github.com/babylonchain/babylon/pull/462
=> Fix bug when delegation does not exists

testutil/helper/gen_blocks.go, x/checkpointing/proposal.go, x/checkpointing/types/types.go, x/checkpointing/vote_ext_test.go
Vote extensions that contain a `BlockHash==nil` pass verification on CometBFT even though `VerifyVoteExtension` should reject them. This PR introduces extra `nil` checks to avoid this situation.
=> hotfix: nil check for resilience against empty vote extensions

x/btcstaking/keeper/power_dist_change_test.go, x/btcstaking/keeper/voting_power_table_test.go
Fixes [BM-1160](https://babylon-chain.atlassian.net/browse/BM-1160)
This PR introduces more fuzz tests on finality provider set rotation, including
- voting power update during the full lifecyle of a slashed finality provider with BTC delegations
- voting power update during the full lifecyle of an expired BTC delegation
- active finality provider set rotation in the presence of changing BTC delegations
This is the final PR to the https://github.com/babylonchain/babylon/tree/base/index-optimise-btcstaking branch, finalising the development of this feature.
=> btcstaking: more tests on finality provider set rotation

.circleci/config.yml, cmd/babylond/cmd/genesis.go
Also change the CircleCI image as it became deprecated.
=> fix: Expedited min deposit should have bbn denom

x/btcstaking/keeper/grpc_query_test.go
Fixes #562
`FuzzFinalityProviderPowerAtHeight` is flaky because `requestHeight` might still be same as `randomHeight`. This happens in https://github.com/babylonchain/babylon/pull/571 as well
Fuzzed locally to verify the fix works
=> fix: fix flaky test `FuzzFinalityProviderPowerAtHeight`

btcstaking/scripts_utils.go, btcstaking/staking_utils_test.go, testutil/bitcoin/utils.go, x/btcstaking/types/btc_slashing_tx_test.go
This PR fixes a bug in `btcstaking/` where constructing the multi sig script will change the order of the caller's input public keys. This PR also adds a test to ensure the sorting functions used by constructing script and constructing witness give reverse results.
Question: should this be a hotfix or we can push it to `dev` for now?
Initially found by @KonradStaniec
=> fix sorting bug in multisig script

cmd/babylond/cmd/genesis.go
Quick fix to our genesis params generator. For genesis to be valid `ExpeditedMinDeposit` must be larger that `MinDeposit`.
Defaults provided by cosmos-sdk, have ratio of `ExpeditedMinDeposit = 5 * MinDeposit`, this pr sets our params to `ExpeditedMinDeposit = 4 * MinDeposit`
=> Increase min expedited deposit

x/btcstaking/keeper/power_dist_change.go, x/btcstaking/keeper/power_dist_change_test.go
There is a non-determinism bug in voting power rotation, where we iterate over the `activeBTCDels` map, which is not deterministic. This PR fixes the bug by first sorting the keys before iterating over them.
- Reproduce: https://github.com/babylonchain/babylon/tree/3d4b194e020aea069c372b33528a4d12f6e88c1f
- Fix and fuzz test: https://github.com/babylonchain/babylon/tree/ed65719b9d1825a3eb1992b56e2c8d8eecc74957
=> fix: fix non-determinism in voting power rotation

docs/staking-script.md
Hello Babylon team,
I am really impressed by the work you are doing. Currently, I am investigating how Bitcoin staking transactions work and I found this document. I believe there are some improvements that can be made. Here are two points I've added:
1. A high-level introduction about who will be involved in the Bitcoin staking transaction.
2. I noticed the terms `btc holder` and `btc staker` are used interchangeably. I have standardized the terminology to `btc staker` for consistency.
Please consider these revisions.
=> Improve the doc of bitcoin staking script

btcstaking/staking.go, x/btcstaking/keeper/msg_server.go, x/btcstaking/types/btc_delegation_test.go, x/btcstaking/types/btc_slashing_tx.go, x/btcstaking/types/btc_slashing_tx_test.go, x/btcstaking/types/btc_undelegation_test.go
This PR unifies the usage of verification functions for various txs in BTC staking, and cleans up some of the APIs.
=> chore: unifying usage of verification functions for btc staking txs

cmd/babylond/cmd/genhelpers/set_btc_delegations_test.go, testutil/datagen/btcstaking.go, x/btcstaking/keeper/grpc_query_test.go, x/btcstaking/keeper/keeper_test.go, x/btcstaking/keeper/msg_server_test.go, x/btcstaking/types/btc_delegation_test.go, x/btcstaking/types/btc_undelegation_test.go
Needed by testing PoS integration. Rust Bitcoin library does not support simnet whereas many datagen functions in Babylon assume simnet.
=> chore: generalising datagen function for BTC delegation

test/e2e/e2e_test.go, x/zoneconcierge/keeper/hooks.go
- When we have a phase-2 IBC channel connection, we are forwarding Bitcoin timestamps and proofs for them
- To generate the proof, we are switching the context to a past block height in order to retrieve the data for a prior state
- Validators that have a high pruning policy (i.e. only keep very few recent blocks), can’t switch to the past state to generate the data, leading to non-determinism
The hotfix involves removing broadcasting of BTC timestamps. We are going to implement a longer term solution in which we do not get historical states for the generation of timestamps for the next testnet. While this is not consensus breaking, this happened only on a recent block, so if we roll back to that block and apply this it consensus won't break for new participants on the ledger.
=> hotfix: Remove broadcasting btc timestamps

test/e2e/e2e_test.go
- CI is broken as on `dev` branch we already uncommented tests for heremes (which were commented out on `main`)
=> Comment out phase2 test

Makefile
We were hitting a weird error in Linux, when iterating over map entries in a smart contract.
This is part of the stack trace for reference:
```
goroutine 459 [running, locked to thread]:
runtime.throw({0x3335f99?, 0xc0057bc178?})
runtime/panic.go:1077 +0x5c fp=0xc0057bc128 sp=0xc0057bc0f8 pc=0x446fbc
runtime.sigpanic()
runtime/signal_unix.go:875 +0x285 fp=0xc0057bc188 sp=0xc0057bc128 pc=0x45e1c5
github.com/CosmWasm/wasmvm/internal/api.cNext({0x7f5f167fabd8?, 0x0?}, 0x7f5f00008f70?, 0x7f5f167fab88?, 0x7f5f167fabe0?, 0x413665?, 0xc004b86340?)
[github.com/CosmWasm/wasmvm@v1.5.2/internal/api/callbacks.go:291](mailto:github.com/CosmWasm/wasmvm@v1.5.2/internal/api/callbacks.go:291) +0xb0 fp=0xc0057bc228 sp=0xc0057bc188 pc=0x1fafc90
_cgoexp_5bd3f86fb1b2_cNext(0x7f5f167faae0)
...
```
A SEGV when …
=> Disable optimized build / blst portable flag

btcstaking/staking.go, btcstaking/staking_test.go
- make `validateSlashingTx` private as it should not be part of the public api, the validation of slashing tx only have point in context of validation of funding/slashing transactions pair
- add check for slashing and funding transaction -  `blockchain.CheckTransactionSanity` which check transactions against BTC rules which are relevant to overlfows and transactions limits.
=> Tighten checks in CheckTransactions function

btcstaking/staking_test.go, go.mod, go.sum
New version of btcd lib  - https://github.com/btcsuite/btcd/releases/tag/v0.24.2
=> bump btcd library

btcstaking/identifiable_staking.go, btcstaking/identifiable_staking_test.go, btcstaking/staking_testvectors_test.go, btcstaking/testvectors/vectors.json, docs/transaction-impl-spec.md
This PR renamed `magicBytes` to `tag` to be consistent with the `tag` field in the global parameters.
=> chore: Rename magic bytes to tag

app/app.go, app/export.go, app/keepers/keepers.go, app/keepers/keys.go, app/keepers/utils.go, app/test_helpers.go, cmd/babylond/cmd/root.go, cmd/babylond/cmd/testnet.go, test/e2e/initialization/init.go, testutil/datagen/genesiskey.go, testutil/helper/helper.go
Closes #609 , step 1 of #698 
This PR refactors the `BabylonApp` to move all keepers into a new struct, including
- Creating a new struct `AppKeepers` that includes all keepers, under `app/keepers`. `BabylonApp` comprises `AppKeepers` such that no interface is changed.
- Moving keeper initialisation into `AppKeepers.InitKeepers` function. The function is parameterised such that all config entries remain in `app/` folder.
This is in line with Osmosis' [approach](https://github.com/osmosis-labs/osmosis/blob/5b92bcb75ca8f9caae83a2a928d2426afa822f82/app/keepers), for formalising [software upgrading](https://github.com/osmosis-labs/osmosis/blob/5796a3faf0411953163511e5635dd9a1c7a46613/app/upgrades) and for modularity. See #698 for more details.
=> refactor: moving keepers to a new struct

x/checkpointing/README.md
This PR updates the links with the correct paths for `bls_key.proto` and `checkpoint.proto` in [x/checkpointing/README.md](https://github.com/babylonchain/babylon/blob/dev/x/checkpointing/README.md#prepareproposal) .
=>  Fixed links in `x/checkpointing/README.md`

Makefile, app/app.go, app/e2e_include_upgrades.go, contrib/images/Makefile, contrib/images/babylond/Dockerfile
- Removed vanilla upgrade from usual build
- Add new file `app/e2e_include_upgrades.go` that is included if there is a build tag e2e and adds the vanilla upgrade to the list of upgrades
=> chore: e2e build tag
