- app/app.go
- cmd/babylond/cmd/flags.go
- cmd/babylond/cmd/genesis.go
- cmd/babylond/cmd/testnet.go
- go.mod
- test/e2e/initialization/node.go
- x/btclightclient/keeper/state_test.go
It will be necessary to setup some block gas limit when launching our testnet with smart contracts enabled
> Use block gas limit when defining genesis

- go.mod
- go.sum
-bumps wasmd to stable version
> Bump wasmd to stable

- go.mod
- go.sum
bumps comet bft  to 0.37.2 to fix - https://github.com/babylonchain/babylon/security/dependabot/16
> Bump comet bft

- README.md
> README: Add medium link

- README.md
- docs/README.md
- docs/architecture.md
- docs/staking-script.md
This PR
- updates the README file w.r.t. the new BTC staking protocol and the latest implementation,
- fixes typos and adds links to our new documents, and
- minor fixes to make linter happy.
> doc: updade README and make linter happy

- x/btclightclient/README.md
A lot of small syntax suggestions.
> BTC light client docs syntax suggestions

- cmd/babylond/cmd/root.go
- fixes wiring to fix unjail command
> fix wiring for cmd

- x/btcstaking/types/pop.go
Small pr which:
- refactors out separate function for bip322 pop verification
- uses it in babylon pop verification
> generic function for bip322 pop

- x/epoching/keeper/drop_validator_msg_decorator.go
fix `ctx.BlockHeight()` in antehandler
> fix ante handler block height

- README.md
This PR adds hardware requirements of running a Babylon node. Spec is based on https://babylon-chain.atlassian.net/wiki/spaces/BABYLON/pages/196280352/bbn-test-3+System+Requirements+WIP and format follows https://github.com/osmosis-labs/osmosis
> doc: hardware requirement

- x/btcstaking/client/cli/query.go
- x/btcstaking/client/cli/tx.go
This PR adds a query to finality provider with the given BTC PK.
Context: https://babylon-chain.slack.com/archives/C06CJ0J6UJ3/p1707884423920019?thread_ts=1707882635.267279&cid=C06CJ0J6UJ3
> btcstaking: query finality provider

- app/test_helpers.go
- btcstaking/types.go
- proto/babylon/zoneconcierge/v1/zoneconcierge.proto
- x/btccheckpoint/keeper/submissions.go
- x/btccheckpoint/types/types.go
- x/zoneconcierge/types/zoneconcierge.pb.go
When I read the code, I found some typo
I fixed them as possible as I can
> fixes some mistakes

- x/btcstaking/keeper/finality_providers.go
- x/btcstaking/keeper/keeper.go
- x/btcstaking/keeper/msg_server.go
- x/btcstaking/keeper/power_dist_change.go
This PR addresses leftover comments under https://github.com/babylonchain/babylon/pull/461
> btcstaking: addressing leftover minor comments

- types/btc_schnorr_sig.go
- x/btcstaking/keeper/btc_delegators.go
- x/btcstaking/keeper/keeper.go
- x/btcstaking/types/btc_slashing_tx.go
- x/btcstaking/types/incentive.go
- x/btcstaking/types/msg.go
Fixes:
- unmarshalling performance
- improved iteration over delegations
> Hot fix perf

- x/finality/keeper/evidence.go
- x/finality/keeper/msg_server_test.go
- fixes `HasEvidence` call and add test
> fix checking evidence existance

- wasmbinding/test/custom_query_test.go
- wasmbinding/wasm.go
- x/btcstaking/client/cli/tx.go
- x/btcstaking/keeper/keeper.go
- x/btcstaking/types/expected_keepers.go
- x/btcstaking/types/mocked_keepers.go
- x/checkpointing/genesis.go
- x/checkpointing/keeper/keeper.go
- x/checkpointing/types/errors.go
- x/finality/keeper/keeper.go
- x/finality/keeper/msg_server.go
- x/finality/keeper/msg_server_test.go
- x/finality/types/expected_keepers.go
- x/finality/types/mocked_keepers.go
- x/zoneconcierge/keeper/epochs.go
- x/zoneconcierge/keeper/grpc_query.go
- x/zoneconcierge/keeper/grpc_query_test.go
- x/zoneconcierge/types/expected_keepers.go
- x/zoneconcierge/types/mocked_keepers.go
Addressing comments at https://github.com/babylonchain/babylon/pull/599#issue-comment-box
> chore: finalised epoch 0 at genesis

- crypto/eots/randomness.go
Needed by https://github.com/babylonchain/finality-provider/pull/284
> chore: constructor function for master secret/public randomness

- testutil/datagen/btc_header_chain.go
- testutil/datagen/btc_header_info.go
- x/btclightclient/types/btc_header_info.go
> Datagen BTC lc header info response helpers

- docs/staking-script.md
- docs/transaction-impl-spec.md
Add spec with examples, how to build and sign locking network special transactions:
- staking transaction
- unbonding transaction
> Add implementation spec for locking network transactions

- docs/staking-script.md
- fix first op code in multisig scripts
- fix format of slashing transactions to adapt to timelock on change output
> Few fixes to script docs

- docs/staking-script.md
- test/e2e/btc_staking_e2e_test.go
- test/e2e/configurer/chain/commands.go
- test/e2e/configurer/chain/queries_btcstaking.go
- Add new Tx command to create FeeGrant
- Test to create BTC delegation with staker out of BBN funds and granter paying for the fees
> chore: add test for btc multisig feegrant

- btcstaking/types.go
- btcstaking/witness_utils.go
Add docs to some of the public facing functions
> Add docs to public facing functions

- docs/run-node.md
- docs/staking-script.md
- x/epoching/README.md
> chore: fix typos

- app/app.go
- app/export.go
- app/keepers/keepers.go
- app/keepers/keys.go
- app/keepers/utils.go
- app/test_helpers.go
- app/upgrades/README.md
- app/upgrades/types.go
- app/upgrades/types_test.go
- app/upgrades/vanilla/README.md
- app/upgrades/vanilla/upgrades.go
- app/upgrades/vanilla/upgrades_test.go
- cmd/babylond/cmd/root.go
- cmd/babylond/cmd/testnet.go
- test/e2e/initialization/init.go
- testutil/datagen/genesiskey.go
- testutil/helper/helper.go
- x/checkpointing/module.go
- x/checkpointing/proposal.go
Resolves #698 
This PR implements the feature of supporting software upgrade gov prop.
> feat(gov): software upgrade governance proposal support

- x/btccheckpoint/types/btcutils.go
- x/btccheckpoint/types/btcutils_test.go
Fixes: https://github.com/babylonchain/babylon/issues/694
> Improve extracting data from op_return + add tests

- test/e2e/btc_staking_e2e_test.go
https://github.com/babylonchain/babylon/pull/713 missend another failure scenario test which have the same problem.
> Diable failure scenario in feegranttyped test
